version: v0.13.0

dsn: memory

serve:
  public:
    base_url: http://identity.nx-next-nest-prisma-ory-template.127.0.0.1.sslip.io/kratos/
    cors:
      enabled: true
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://auth.nx-next-nest-prisma-ory-template.127.0.0.1.sslip.io/
  allowed_return_urls:
    - http://auth.nx-next-nest-prisma-ory-template.127.0.0.1.sslip.io/

  methods:
    password:
      enabled: true
    totp:
      config:
        issuer: Kratos
      enabled: true
    lookup_secret:
      enabled: true
    link:
      enabled: true
    code:
      enabled: true

  flows:
    error:
      ui_url: http://auth.nx-next-nest-prisma-ory-template.127.0.0.1.sslip.io/error

    settings:
      ui_url: http://auth.nx-next-nest-prisma-ory-template.127.0.0.1.sslip.io/settings
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      enabled: true
      ui_url: http://auth.nx-next-nest-prisma-ory-template.127.0.0.1.sslip.io/recovery
      use: code

    verification:
      enabled: true
      ui_url: http://auth.nx-next-nest-prisma-ory-template.127.0.0.1.sslip.io/verification
      use: code
      after:
        default_browser_return_url: http://auth.nx-next-nest-prisma-ory-template.127.0.0.1.sslip.io/

    logout:
      after:
        default_browser_return_url: http://auth.nx-next-nest-prisma-ory-template.127.0.0.1.sslip.io/login

    login:
      ui_url: http://auth.nx-next-nest-prisma-ory-template.127.0.0.1.sslip.io/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://auth.nx-next-nest-prisma-ory-template.127.0.0.1.sslip.io/registration
      after:
        password:
          hooks:
            - hook: session
            - hook: show_verification_ui

log:
  level: debug
  format: text
  leak_sensitive_values: true

tracing:
  provider: jaeger
  service_name: ory:kratos
  providers:
    jaeger:
      local_agent_address: jaeger:6831
      sampling:
        server_url: http://jaeger:5778/sampling

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

cookies:
  domain: nx-next-nest-prisma-ory-template.127.0.0.1.sslip.io
  same_site: Lax

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
