#######################################
#         Kratos Access Rules         #
#######################################
- id: "ory:kratos:public"
  upstream:
    preserve_host: true
    url: "http://kratos:4433"
    strip_path: /kratos
  match:
    url: http://identity.nx-next-nest-prisma-ory-template.<127\.0\.0\.1\.sslip\.io|com>/kratos/<.*>
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop
