name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  docker:
    name: docker-${{ matrix.app }}
    strategy:
      fail-fast: false
      matrix:
        app: ['api', 'www']
    concurrency:
      group: 'docker-${{ matrix.app }}'
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/$GITHUB_REPOSITORY
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          context: .
          file: ./apps/${{ matrix.app }}/Dockerfile
          platforms: linux/amd64, linux/arm64, linux/arm/v7
          provenance: true
          sbom: true

  create-github-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get tag name
        id: tag
        run: echo ::set-output name=tag_name::${GITHUB_REF#refs/tags/}

      - name: Create GitHub Release
        uses: taiki-e/create-gh-release-action@v1
        with:
          title: Release ${{ steps.tag.outputs.tag_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

  bump-version:
    runs-on: ubuntu-latest
    concurrency:
      group: 'bump-version'
      cancel-in-progress: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7

      - name: Format version
        id: formatVersion
        run: |
          echo "buildVersion=${{ steps.gitversion.outputs.MajorMinorPatch }}" >> "$GITHUB_OUTPUT"

      - name: Bump version
        run: |
          sed -i "/\"version\":/c\  \"version\": \"${{ steps.formatVersion.outputs.buildVersion }}\"," package.json

      - name: Commit version bump
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'build: bump version to ${{ steps.formatVersion.outputs.buildVersion }} [skip ci]'
          commit_options: '-a'
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
